### ISSUE TITLE
No controller profile found for type ARFukuoka.MixedReality.Toolkit.Nreal.Input.NrealController

### ISSUE THREAD

**Issue by StevenJuan** [TakashiYoshinaga/MRTK-Profiles-for-NrealLight#1]
Hello! I import follow this steps：
1.NRSDK1.6.0
2.MRTK2.7.2Foundation
3.NrealLightHandTracking.unitypackage

then run sample scene shows：
No controller profile found for type ARFukuoka.MixedReality.Toolkit.Nreal.Input.NrealController; please ensure all controllers are defined in the configured MixedRealityControllerConfigurationProfile.

oh sorry I solve this, 4.27 need reimport mrtk，4.28 restart editor。

**Comment by TakashiYoshinaga** [comment]
Thank you for your feedback!
