### ISSUE TITLE
No image in left eye

### ISSUE THREAD

**Issue by MrFarePlay** [TakashiYoshinaga/MRTK-Profiles-for-NrealLight#11]
Good day. Amazing work btw

I've having an issue when testing the sample scenes. Everything works fine and I can use hand tracking to control and interact with the objects.

But am I having an issue where only the right eye is showing the scene. The left eye does not show anything. I moved around the room a bit thinking it could be a clipping problem (because both left and right cameras don't have the same setting for some reason). But nothing shows at all in the left eye.

Unity version 2021.3.8f1
NRSDK 1.9.3
Microsoft.MixedReality.Toolkit.Unity.Foundation.2.8.2

**Comment by TakashiYoshinaga** [comment]
Fixed.
Please see below.
https://github.com/TakashiYoshinaga/MRTK-Profiles-for-NrealLight/releases/tag/v1.0.0
